### ISSUE TITLE
Compile on AXi

### ISSUE THREAD

**Issue by dportugal-solutionz** [sentry07/vscode-amx-netlinx#6]
Please add ability to compile AXI files.

Thanks,

**Comment by sentry07** [comment]
Just AXI files? The extension also supports AXB and LIB files. Do those need to be compiled as well?

**Comment by dportugal-solutionz** [comment]
Pressing Shift+Ctrl+B is on an AXI file doesn’t bring up the compile options.


Daniel Portugal
A/V Programmer

D: 714.367.2905 C: 562.519.6972
Daniel.Portugal@spinitar.com<mailto:Daniel.Portugal@spinitar.com>
www.spinitar.com<https://www.spinitar.com/>
[cid:image002.png@01D61FFD.AE907CE0]

**Comment by sentry07** [comment]
0.6.1 is sent to the VSCode Marketplace. As soon as it's verified it will be available to update. Should be 10-15 minutes at most.

**Comment by dportugal-solutionz** [comment]
Thanks for the update! It works


Daniel Portugal
A/V Programmer

D: 714.367.2905 C: 562.519.6972
Daniel.Portugal@spinitar.com<mailto:Daniel.Portugal@spinitar.com>
www.spinitar.com<https://www.spinitar.com/>
[cid:image002.png@01D621F7.8A61EB00]
